name: bloc
description: "An alternative BLoC implementation"
version: 0.0.1

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.28.0

dev_dependencies:
  flutter_lints: ^4.0.0
